package constant

type MENU_CODE string

const (
	M_USER         MENU_CODE = "M_USER"
	M_LOG_AUDIT    MENU_CODE = "M_LOG_AUDIT"
	M_LOG_SYSTEM   MENU_CODE = "M_LOG_SYSTEM"
	M_POLICY_ROLE  MENU_CODE = "M_POLICY_ROLE"
	M_POLICY_LOGIN MENU_CODE = "M_POLICY_LOGIN"

	// M_S_COULMN_DEF MENU_CODE = "M_S_COULMN_DEF"

	M_WORK   MENU_CODE = "M_WORK"
	M_PRE    MENU_CODE = "M_PRE"
	M_TARGET MENU_CODE = "M_TARGET"
	M_RISK   MENU_CODE = "M_RISK"
	M_LEVEL  MENU_CODE = "M_LEVEL"
	M_PSEUDO MENU_CODE = "M_PSEUDO"
	M_JOIN   MENU_CODE = "M_JOIN"
	M_ASSESS MENU_CODE = "M_ASSESS"
	M_POST   MENU_CODE = "M_POST"
)
